# Generated by Django 5.2.5 on 2025-11-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_name_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enrollment_Id', models.CharField(max_length=100)),
                ('Student_Id', models.CharField(max_length=100)),
                ('Course_Id', models.CharField(max_length=100)),
                ('Enrollment_date', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
