# Generated by Django 5.2.5 on 2025-11-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_enrollment_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule_Id', models.CharField(max_length=100)),
                ('Course_Id', models.CharField(max_length=100)),
                ('Instructor_Name', models.CharField(max_length=100)),
                ('Day_time', models.DateTimeField(max_length=100)),
                ('Room_Number', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Enrollment_date',
            field=models.DateTimeField(max_length=100),
        ),
    ]
