# Generated by Django 5.2.5 on 2025-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_schedule_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade_Id', models.CharField(max_length=100)),
                ('Student_Id', models.CharField(max_length=100)),
                ('Course_ID', models.CharField(max_length=100)),
                ('Semester', models.CharField(max_length=100)),
                ('Final_grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Day_time',
            field=models.CharField(max_length=100),
        ),
    ]
