# Generated by Django 5.2.5 on 2025-11-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Id', models.CharField(max_length=100)),
                ('Course_Name', models.CharField(max_length=100)),
                ('Course_Description', models.CharField(max_length=100)),
                ('Course_Unit', models.CharField(max_length=100)),
                ('Department_Unit', models.EmailField(max_length=100)),
            ],
        ),
    ]
