# Generated by Django 5.2.8 on 2025-11-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Unit',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='Department_Unit',
            field=models.IntegerField(max_length=100),
        ),
    ]
