# Generated by Django 5.2.8 on 2025-11-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_course_course_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Date_of_Bith',
            new_name='Date_of_Birth',
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_Unit',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='Department_Unit',
            field=models.IntegerField(max_length=1),
        ),
    ]
