# Generated by Django 5.2.8 on 2025-11-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_rename_date_of_bith_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Contact',
            new_name='Student_Num',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Date_of_Birth',
            new_name='Year_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Student_Id',
        ),
        migrations.AddField(
            model_name='student',
            name='LRN',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_Unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Department_Unit',
            field=models.IntegerField(),
        ),
    ]
