# Generated by Django 5.2.8 on 2025-11-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_rename_contact_student_student_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='Course_ID',
            new_name='GPA',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='Final_grade',
            new_name='Grade_Value',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='Grade_Id',
            new_name='Remarks',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='Semester',
            new_name='Student_num',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='Student_Id',
            new_name='Subject_Id',
        ),
    ]
