# Generated by Django 5.2.8 on 2025-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_rename_course_id_grade_gpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Relationships', models.CharField(max_length=100)),
                ('Contact_num', models.DateTimeField(max_length=100)),
                ('Student_Contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
