# Generated by Django 5.2.8 on 2025-11-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_guardian_delete_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instructor', models.CharField(max_length=100)),
                ('Fullname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Days', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
