# Generated by Django 5.2.8 on 2025-11-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_instructor_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_id', models.CharField(max_length=100)),
                ('Subject_Name', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100)),
                ('Schedule', models.IntegerField()),
                ('Room', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
