# Generated by Django 5.2.8 on 2025-11-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_subject_delete_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='Contact_num',
        ),
        migrations.AddField(
            model_name='guardian',
            name='Guardian_Contact',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='Grade_Value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='Student_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='Student_Contact',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='Contact',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Room',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Schedule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Unit',
            field=models.IntegerField(),
        ),
    ]
